<?php
/**
 * Created by PhpStorm.
 * User: monster
 * Date: 26/08/2015
 * Time: 16:58
 */

/**
 * Implements hook_menu().
 */
function leek_menu()
{
  $items = array();

  $items['leek/zingmp3'] = array(
    'label' => 'Zing MP3 Downloader',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('zingmp3_download'),
    'access callback' => TRUE,
  );

  return $items;
}

function zingmp3_download($form, $form_state) {
  $form['link'] = array(
    '#type' => 'textfield',
    '#title' => 'Link',
    '#required' => TRUE,
    '#description' => 'Enter your album link here',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Download',
  );

  return $form;
}

function zingmp3_download_submit($form, &$form_state) {
  $link = $form_state['values']['link'];
  $coookie = "zsid=nZP-.106083373.20.B4wVdSO-csZhYibknZwRQ6t3ighbSVkWnr05i9DQcs36FfjUz0YlM_uBhcN6GPje";

//  $header = a?drupal_http_request($link,$options);
//  $data = gzdecode($content->data, $content->headers['content-length']);
//  $data = gzinflate($content->data, $content->headers['content-length']);
//  print $data;
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $link);
  curl_setopt($ch,CURLOPT_ENCODING , "");
  curl_setopt($ch, CURLOPT_HEADER, false);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_COOKIE, $coookie);
  $a = curl_exec($ch);
  $url = strpos($a, 'data-xml');
  $u = '';
  $dem = 0;
  if ($url > 1) {
    for($i = $url; ; $i++) {
      if ($a[$i] == '"' || $dem == 1) {
        $dem ++;
      }
      if ($dem == 3 || $i > $url + 100) {
        break;
      }
      if ($dem == 2) {
        $u .= $a[$i];
      }
    }
  }

  if (strpos($u, 'http://') >= 0) {
    $content = drupal_http_request($u);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $u);
    curl_setopt($ch,CURLOPT_ENCODING , "");
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_COOKIE, $coookie);
    $input_lines = curl_exec($ch);
    preg_match_all('/http:\/\/mp3.zing.vn\/xml\/load-song\/(.*)]]>/', $input_lines, $output_array);

    if (!empty($output_array)) {
      $file = fopen('public://download_mp3.txt', 'wb');
      $items = $output_array[1];
      foreach($items as $item) {
        $item = 'http://mp3.zing.vn/xml/load-song/' . $item;
        $item = get_redirected_link($item);
        if (!empty($item)) {
          fwrite($file, $item . "\r\n");
        }
      }
      fclose($file);
      DownloadFile('public://download_mp3.txt');
    }
  } else {
    drupal_set_message('Download failed');
  }
}

function gzdecoder($d){
  $f=ord(substr($d,3,1));
  $h=10;$e=0;
  if($f&4){
    $e=unpack('v',substr($d,10,2));
    $e=$e[1];$h+=2+$e;
  }
  if($f&8){
    $h=strpos($d,chr(0),$h)+1;
  }
  if($f&16){
    $h=strpos($d,chr(0),$h)+1;
  }
  if($f&2){
    $h+=2;
  }
  $u = gzinflate(substr($d,$h));
  if($u===FALSE){
    $u=$d;
  }
  return $u;
}

function get_redirected_link($url){

  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_HEADER, true);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_COOKIE, "zsid=nZP-.106083373.20.B4wVdSO-csZhYibknZwRQ6t3ighbSVkWnr05i9DQcs36FfjUz0YlM_uBhcN6GPje");
  $a = curl_exec($ch);
//print_r($a);
//echo"<br>";
  if(preg_match('#Location: (.*)#', $a, $r)){
    $l = trim($r[1]);
    //echo $l;
  }else ;

  if (isset($l)) {
    return $l;
  }
  return FALSE;
}

