<?php
/**
 * Created by PhpStorm.
 * User: monster
 * Date: 21/08/2015
 * Time: 11:21
 */

/**
 * Implements hook_menu().
 */
function train255_menu()
{
  $items['subscription_rest_package/export'] = array(
    'title' => 'Exporting',
    'page callback' => 'export_data_subscription_rest_package',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function export_data_subscription_rest_package()
{
  $data = cache_get('subscription_rest_package_data', 'cached_subscription_rest_package');
  foreach ($data->data as $key => $item_row) {
    $item_row = (array)($item_row);
    $item_row1 = array();
    foreach ($item_row as $key2 => $item) {
      if ($key2 != 'meta') {
        $item_row1[$key2] = $item;
      }
    }
    if ($key == 0) {
      print  '"' . implode('","', array_keys($item_row1)) . '"</br>';
    }
    print '"' . implode('","', $item_row1) . '"</br>';
  }

}

/**
 * Implements hook_views_api().
 */
function train255_views_api()
{
  return array(
    'api' => 3,
  );
}